"""step78: add infrastructure_costs and budget_thresholds tables

Revision ID: 059873c4f75a
Revises: d3db0ff70c72
Create Date: 2026-08-14 11:06:56.304413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059873c4f75a'
down_revision: Union[str, Sequence[str], None] = 'd3db0ff70c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('monthly_budget_usd', sa.Float(), nullable=False),
    sa.Column('warning_percent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_thresholds_id'), 'budget_thresholds', ['id'], unique=False)
    op.create_table('infrastructure_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('monthly_cost_usd', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_costs_id'), 'infrastructure_costs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_infrastructure_costs_id'), table_name='infrastructure_costs')
    op.drop_table('infrastructure_costs')
    op.drop_index(op.f('ix_budget_thresholds_id'), table_name='budget_thresholds')
    op.drop_table('budget_thresholds')
    # ### end Alembic commands ###
