"""add financial records

Revision ID: 07d681c31deb
Revises: aec92e14d604
Create Date: 2026-08-13 07:01:33.377776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d681c31deb'
down_revision: Union[str, Sequence[str], None] = 'aec92e14d604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('solar_savings', sa.Float(), nullable=False),
    sa.Column('grid_purchase_cost', sa.Float(), nullable=False),
    sa.Column('battery_savings', sa.Float(), nullable=False),
    sa.Column('energy_sales_revenue', sa.Float(), nullable=False),
    sa.Column('total_savings', sa.Float(), nullable=False),
    sa.Column('net_energy_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'date', name='uq_financial_records_factory_date')
    )
    op.create_index(op.f('ix_financial_records_date'), 'financial_records', ['date'], unique=False)
    op.create_index(op.f('ix_financial_records_factory_id'), 'financial_records', ['factory_id'], unique=False)
    op.create_index(op.f('ix_financial_records_id'), 'financial_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_records_id'), table_name='financial_records')
    op.drop_index(op.f('ix_financial_records_factory_id'), table_name='financial_records')
    op.drop_index(op.f('ix_financial_records_date'), table_name='financial_records')
    op.drop_table('financial_records')
    # ### end Alembic commands ###
