"""add financial transactions and extend financial record and factory

Revision ID: 22e5c4064623
Revises: 43c50e79ab42
Create Date: 2026-08-13 09:25:51.650982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22e5c4064623'
down_revision: Union[str, Sequence[str], None] = '43c50e79ab42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('energy_kwh', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_transactions_factory_id'), 'financial_transactions', ['factory_id'], unique=False)
    op.create_index('ix_financial_transactions_factory_timestamp', 'financial_transactions', ['factory_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_financial_transactions_id'), 'financial_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_timestamp'), 'financial_transactions', ['timestamp'], unique=False)
    op.add_column('factories', sa.Column('solar_installation_cost', sa.Float(), nullable=True))
    op.add_column('financial_records', sa.Column('solar_generation_kwh', sa.Float(), nullable=False, server_default='0'))
    op.add_column('financial_records', sa.Column('solar_used_kwh', sa.Float(), nullable=False, server_default='0'))
    op.add_column('financial_records', sa.Column('grid_import_kwh', sa.Float(), nullable=False, server_default='0'))
    op.add_column('financial_records', sa.Column('grid_export_kwh', sa.Float(), nullable=False, server_default='0'))
    op.add_column('financial_records', sa.Column('battery_degradation_cost', sa.Float(), nullable=False, server_default='0'))
    op.add_column('financial_records', sa.Column('load_shift_savings', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_records', 'load_shift_savings')
    op.drop_column('financial_records', 'battery_degradation_cost')
    op.drop_column('financial_records', 'grid_export_kwh')
    op.drop_column('financial_records', 'grid_import_kwh')
    op.drop_column('financial_records', 'solar_used_kwh')
    op.drop_column('financial_records', 'solar_generation_kwh')
    op.drop_column('factories', 'solar_installation_cost')
    op.drop_index(op.f('ix_financial_transactions_timestamp'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_id'), table_name='financial_transactions')
    op.drop_index('ix_financial_transactions_factory_timestamp', table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_factory_id'), table_name='financial_transactions')
    op.drop_table('financial_transactions')
    # ### end Alembic commands ###
