"""add consecutive_error_count and last_error_message to devices

Revision ID: 2365e3fa794e
Revises: 269c77317f2f
Create Date: 2026-08-14 04:48:49.850850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2365e3fa794e'
down_revision: Union[str, Sequence[str], None] = '269c77317f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('consecutive_error_count', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('devices', 'consecutive_error_count', server_default=None)
    op.add_column('devices', sa.Column('last_error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_error_message')
    op.drop_column('devices', 'consecutive_error_count')
    # ### end Alembic commands ###
