"""add battery soc bounds and efficiency

Revision ID: 253c21102162
Revises: 729dd69895e2
Create Date: 2026-08-13 08:38:04.342140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253c21102162'
down_revision: Union[str, Sequence[str], None] = '729dd69895e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battery_systems', sa.Column('min_soc_percent', sa.Float(), nullable=False, server_default='10'))
    op.add_column('battery_systems', sa.Column('max_soc_percent', sa.Float(), nullable=False, server_default='95'))
    op.add_column('battery_systems', sa.Column('efficiency_percent', sa.Float(), nullable=False, server_default='90'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('battery_systems', 'efficiency_percent')
    op.drop_column('battery_systems', 'max_soc_percent')
    op.drop_column('battery_systems', 'min_soc_percent')
    # ### end Alembic commands ###
