"""add escalated_at to notifications

Revision ID: 269c77317f2f
Revises: 41dc198be01b
Create Date: 2026-08-14 04:38:43.559695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269c77317f2f'
down_revision: Union[str, Sequence[str], None] = '41dc198be01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'escalated_at')
    # ### end Alembic commands ###
