"""add battery_degradation_cost_per_kwh to factories

Revision ID: 41dc198be01b
Revises: 8b7d330e58e8
Create Date: 2026-08-14 04:33:03.883469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41dc198be01b'
down_revision: Union[str, Sequence[str], None] = '8b7d330e58e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factories', sa.Column('battery_degradation_cost_per_kwh', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factories', 'battery_degradation_cost_per_kwh')
    # ### end Alembic commands ###
