"""add recommendation windows scoring audit log and production lines

Revision ID: 43c50e79ab42
Revises: 5eab55b19325
Create Date: 2026-08-13 09:13:57.641940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c50e79ab42'
down_revision: Union[str, Sequence[str], None] = '5eab55b19325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('power_kw', sa.Float(), nullable=False),
    sa.Column('flexible', sa.Boolean(), nullable=False),
    sa.Column('minimum_run_time_hours', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_lines_factory_id'), 'production_lines', ['factory_id'], unique=False)
    op.create_index(op.f('ix_production_lines_id'), 'production_lines', ['id'], unique=False)
    op.create_table('recommendation_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_audit_logs_id'), 'recommendation_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_audit_logs_recommendation_id'), 'recommendation_audit_logs', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_audit_logs_user_id'), 'recommendation_audit_logs', ['user_id'], unique=False)
    op.add_column('recommendations', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recommendations', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recommendations', sa.Column('net_benefit', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'updated_at')
    op.drop_column('recommendations', 'score')
    op.drop_column('recommendations', 'net_benefit')
    op.drop_column('recommendations', 'end_time')
    op.drop_column('recommendations', 'start_time')
    op.drop_index(op.f('ix_recommendation_audit_logs_user_id'), table_name='recommendation_audit_logs')
    op.drop_index(op.f('ix_recommendation_audit_logs_recommendation_id'), table_name='recommendation_audit_logs')
    op.drop_index(op.f('ix_recommendation_audit_logs_id'), table_name='recommendation_audit_logs')
    op.drop_table('recommendation_audit_logs')
    op.drop_index(op.f('ix_production_lines_id'), table_name='production_lines')
    op.drop_index(op.f('ix_production_lines_factory_id'), table_name='production_lines')
    op.drop_table('production_lines')
    # ### end Alembic commands ###
