"""step83_add_target_service

Revision ID: 503a80766de3
Revises: 059873c4f75a
Create Date: 2026-08-14 15:19:58.974580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503a80766de3'
down_revision: Union[str, Sequence[str], None] = '059873c4f75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'recovery_drills',
        sa.Column('target_service', sa.String(length=50), nullable=False, server_default='Database'),
    )
    op.alter_column('recovery_drills', 'target_service', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_drills', 'target_service')
    # ### end Alembic commands ###
