"""add energy readings

Revision ID: 546b90304eb1
Revises: 87a417bc1485
Create Date: 2026-08-13 06:28:36.644583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546b90304eb1'
down_revision: Union[str, Sequence[str], None] = '87a417bc1485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('solar_generation_kwh', sa.Float(), nullable=False),
    sa.Column('consumption_kwh', sa.Float(), nullable=False),
    sa.Column('grid_import_kwh', sa.Float(), nullable=False),
    sa.Column('grid_export_kwh', sa.Float(), nullable=False),
    sa.Column('battery_charge_kwh', sa.Float(), nullable=False),
    sa.Column('battery_discharge_kwh', sa.Float(), nullable=False),
    sa.Column('battery_soc_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_readings_factory_id'), 'energy_readings', ['factory_id'], unique=False)
    op.create_index(op.f('ix_energy_readings_id'), 'energy_readings', ['id'], unique=False)
    op.create_index(op.f('ix_energy_readings_timestamp'), 'energy_readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_energy_readings_timestamp'), table_name='energy_readings')
    op.drop_index(op.f('ix_energy_readings_id'), table_name='energy_readings')
    op.drop_index(op.f('ix_energy_readings_factory_id'), table_name='energy_readings')
    op.drop_table('energy_readings')
    # ### end Alembic commands ###
