"""add source to energy_readings for device aggregation sync

Revision ID: 5c0e41b9373e
Revises: 96eaf18f5318
Create Date: 2026-08-13 13:51:48.439320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0e41b9373e'
down_revision: Union[str, Sequence[str], None] = '96eaf18f5318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_readings', sa.Column('source', sa.String(length=20), nullable=False, server_default='MANUAL'))
    op.alter_column('energy_readings', 'source', server_default=None)
    op.create_unique_constraint('uq_energy_readings_factory_timestamp_source', 'energy_readings', ['factory_id', 'timestamp', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_energy_readings_factory_timestamp_source', 'energy_readings', type_='unique')
    op.drop_column('energy_readings', 'source')
    # ### end Alembic commands ###
