"""step84_add_performance_indexes

Revision ID: 5c46123306ad
Revises: 503a80766de3
Create Date: 2026-08-14 15:38:26.129305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c46123306ad'
down_revision: Union[str, Sequence[str], None] = '503a80766de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_org_created_at', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_security_events_created_at'), 'security_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_events_created_at'), table_name='security_events')
    op.drop_index('ix_audit_logs_org_created_at', table_name='audit_logs')
    # ### end Alembic commands ###
