"""add solar forecasts

Revision ID: 5eab55b19325
Revises: 253c21102162
Create Date: 2026-08-13 09:05:49.960636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eab55b19325'
down_revision: Union[str, Sequence[str], None] = '253c21102162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solar_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_power_kw', sa.Float(), nullable=False),
    sa.Column('expected_energy_kwh', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'timestamp', name='uq_solar_forecasts_factory_timestamp')
    )
    op.create_index(op.f('ix_solar_forecasts_factory_id'), 'solar_forecasts', ['factory_id'], unique=False)
    op.create_index(op.f('ix_solar_forecasts_id'), 'solar_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_solar_forecasts_timestamp'), 'solar_forecasts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solar_forecasts_timestamp'), table_name='solar_forecasts')
    op.drop_index(op.f('ix_solar_forecasts_id'), table_name='solar_forecasts')
    op.drop_index(op.f('ix_solar_forecasts_factory_id'), table_name='solar_forecasts')
    op.drop_table('solar_forecasts')
    # ### end Alembic commands ###
