"""add electricity prices

Revision ID: 6675b10975a3
Revises: 546b90304eb1
Create Date: 2026-08-13 06:46:54.102984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6675b10975a3'
down_revision: Union[str, Sequence[str], None] = '546b90304eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electricity_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('buy_price_per_kwh', sa.Float(), nullable=False),
    sa.Column('sell_price_per_kwh', sa.Float(), nullable=False),
    sa.Column('price_level', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_electricity_prices_factory_id'), 'electricity_prices', ['factory_id'], unique=False)
    op.create_index(op.f('ix_electricity_prices_id'), 'electricity_prices', ['id'], unique=False)
    op.create_index(op.f('ix_electricity_prices_timestamp'), 'electricity_prices', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_electricity_prices_timestamp'), table_name='electricity_prices')
    op.drop_index(op.f('ix_electricity_prices_id'), table_name='electricity_prices')
    op.drop_index(op.f('ix_electricity_prices_factory_id'), table_name='electricity_prices')
    op.drop_table('electricity_prices')
    # ### end Alembic commands ###
