"""add users, factories, solar systems, battery systems, energy meters

Revision ID: 6acd81ae3201
Revises: 161454d50ea8
Create Date: 2026-08-13 05:59:07.906900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6acd81ae3201'
down_revision: Union[str, Sequence[str], None] = '161454d50ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('solar_capacity_kw', sa.Float(), nullable=True),
    sa.Column('battery_capacity_kwh', sa.Float(), nullable=True),
    sa.Column('grid_connection_type', sa.String(length=100), nullable=True),
    sa.Column('electricity_tariff', sa.String(length=100), nullable=True),
    sa.Column('working_hours_start', sa.Time(), nullable=True),
    sa.Column('working_hours_end', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factories_id'), 'factories', ['id'], unique=False)
    op.create_index(op.f('ix_factories_organization_id'), 'factories', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('battery_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('capacity_kwh', sa.Float(), nullable=False),
    sa.Column('usable_capacity_kwh', sa.Float(), nullable=True),
    sa.Column('state_of_charge_percent', sa.Float(), nullable=True),
    sa.Column('state_of_health_percent', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('cycle_count', sa.Integer(), nullable=False),
    sa.Column('charge_rate_kw', sa.Float(), nullable=True),
    sa.Column('discharge_rate_kw', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battery_systems_factory_id'), 'battery_systems', ['factory_id'], unique=True)
    op.create_index(op.f('ix_battery_systems_id'), 'battery_systems', ['id'], unique=False)
    op.create_table('energy_meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('meter_type', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_meters_factory_id'), 'energy_meters', ['factory_id'], unique=False)
    op.create_index(op.f('ix_energy_meters_id'), 'energy_meters', ['id'], unique=False)
    op.create_table('solar_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('installed_capacity_kw', sa.Float(), nullable=False),
    sa.Column('panel_count', sa.Integer(), nullable=True),
    sa.Column('inverter_brand', sa.String(length=255), nullable=True),
    sa.Column('efficiency_percent', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_systems_factory_id'), 'solar_systems', ['factory_id'], unique=True)
    op.create_index(op.f('ix_solar_systems_id'), 'solar_systems', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solar_systems_id'), table_name='solar_systems')
    op.drop_index(op.f('ix_solar_systems_factory_id'), table_name='solar_systems')
    op.drop_table('solar_systems')
    op.drop_index(op.f('ix_energy_meters_id'), table_name='energy_meters')
    op.drop_index(op.f('ix_energy_meters_factory_id'), table_name='energy_meters')
    op.drop_table('energy_meters')
    op.drop_index(op.f('ix_battery_systems_id'), table_name='battery_systems')
    op.drop_index(op.f('ix_battery_systems_factory_id'), table_name='battery_systems')
    op.drop_table('battery_systems')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_factories_organization_id'), table_name='factories')
    op.drop_index(op.f('ix_factories_id'), table_name='factories')
    op.drop_table('factories')
    # ### end Alembic commands ###
