"""add energy monthly and extend hourly daily with completeness and peaks

Revision ID: 6f87b2117012
Revises: 22e5c4064623
Create Date: 2026-08-13 09:36:49.372260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f87b2117012'
down_revision: Union[str, Sequence[str], None] = '22e5c4064623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_monthly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('solar_kwh', sa.Float(), nullable=False),
    sa.Column('consumption_kwh', sa.Float(), nullable=False),
    sa.Column('grid_import_kwh', sa.Float(), nullable=False),
    sa.Column('grid_export_kwh', sa.Float(), nullable=False),
    sa.Column('total_savings', sa.Float(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('data_completeness', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'month', name='uq_energy_monthly_factory_month')
    )
    op.create_index(op.f('ix_energy_monthly_factory_id'), 'energy_monthly', ['factory_id'], unique=False)
    op.create_index(op.f('ix_energy_monthly_month'), 'energy_monthly', ['month'], unique=False)
    op.add_column('energy_daily', sa.Column('data_completeness', sa.Float(), nullable=False, server_default='100'))
    op.add_column('energy_daily', sa.Column('peak_demand_kw', sa.Float(), nullable=True))
    op.add_column('energy_daily', sa.Column('peak_demand_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('energy_daily', sa.Column('peak_solar_kw', sa.Float(), nullable=True))
    op.add_column('energy_hourly', sa.Column('data_completeness', sa.Float(), nullable=False, server_default='100'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('energy_hourly', 'data_completeness')
    op.drop_column('energy_daily', 'peak_solar_kw')
    op.drop_column('energy_daily', 'peak_demand_time')
    op.drop_column('energy_daily', 'peak_demand_kw')
    op.drop_column('energy_daily', 'data_completeness')
    op.drop_index(op.f('ix_energy_monthly_month'), table_name='energy_monthly')
    op.drop_index(op.f('ix_energy_monthly_factory_id'), table_name='energy_monthly')
    op.drop_table('energy_monthly')
    # ### end Alembic commands ###
