"""add device energy readings and hourly daily aggregates

Revision ID: 729dd69895e2
Revises: fcb8a0250c9b
Create Date: 2026-08-13 08:30:24.368425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729dd69895e2'
down_revision: Union[str, Sequence[str], None] = 'fcb8a0250c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('solar_kwh', sa.Float(), nullable=False),
    sa.Column('consumption_kwh', sa.Float(), nullable=False),
    sa.Column('grid_import_kwh', sa.Float(), nullable=False),
    sa.Column('grid_export_kwh', sa.Float(), nullable=False),
    sa.Column('battery_charge_kwh', sa.Float(), nullable=False),
    sa.Column('battery_discharge_kwh', sa.Float(), nullable=False),
    sa.Column('data_quality', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'date', name='uq_energy_daily_factory_date')
    )
    op.create_index(op.f('ix_energy_daily_date'), 'energy_daily', ['date'], unique=False)
    op.create_index(op.f('ix_energy_daily_factory_id'), 'energy_daily', ['factory_id'], unique=False)
    op.create_table('energy_hourly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('hour', sa.DateTime(timezone=True), nullable=False),
    sa.Column('solar_kwh', sa.Float(), nullable=False),
    sa.Column('consumption_kwh', sa.Float(), nullable=False),
    sa.Column('grid_import_kwh', sa.Float(), nullable=False),
    sa.Column('grid_export_kwh', sa.Float(), nullable=False),
    sa.Column('battery_charge_kwh', sa.Float(), nullable=False),
    sa.Column('battery_discharge_kwh', sa.Float(), nullable=False),
    sa.Column('data_quality', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'hour', name='uq_energy_hourly_factory_hour')
    )
    op.create_index(op.f('ix_energy_hourly_factory_id'), 'energy_hourly', ['factory_id'], unique=False)
    op.create_index(op.f('ix_energy_hourly_hour'), 'energy_hourly', ['hour'], unique=False)
    op.create_table('device_energy_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('power_kw', sa.Float(), nullable=False),
    sa.Column('energy_kwh', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_energy_readings_device_id'), 'device_energy_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_energy_readings_factory_id'), 'device_energy_readings', ['factory_id'], unique=False)
    op.create_index('ix_device_energy_readings_factory_timestamp', 'device_energy_readings', ['factory_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_device_energy_readings_id'), 'device_energy_readings', ['id'], unique=False)
    op.create_index(op.f('ix_device_energy_readings_timestamp'), 'device_energy_readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_energy_readings_timestamp'), table_name='device_energy_readings')
    op.drop_index(op.f('ix_device_energy_readings_id'), table_name='device_energy_readings')
    op.drop_index('ix_device_energy_readings_factory_timestamp', table_name='device_energy_readings')
    op.drop_index(op.f('ix_device_energy_readings_factory_id'), table_name='device_energy_readings')
    op.drop_index(op.f('ix_device_energy_readings_device_id'), table_name='device_energy_readings')
    op.drop_table('device_energy_readings')
    op.drop_index(op.f('ix_energy_hourly_hour'), table_name='energy_hourly')
    op.drop_index(op.f('ix_energy_hourly_factory_id'), table_name='energy_hourly')
    op.drop_table('energy_hourly')
    op.drop_index(op.f('ix_energy_daily_factory_id'), table_name='energy_daily')
    op.drop_index(op.f('ix_energy_daily_date'), table_name='energy_daily')
    op.drop_table('energy_daily')
    # ### end Alembic commands ###
