"""step77: add postmortem_corrective_actions table

Revision ID: 7fc16f7c9664
Revises: d79a164452c7
Create Date: 2026-08-14 09:48:28.730796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc16f7c9664'
down_revision: Union[str, Sequence[str], None] = 'd79a164452c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postmortem_corrective_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postmortem_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['postmortem_id'], ['incident_postmortems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postmortem_corrective_actions_id'), 'postmortem_corrective_actions', ['id'], unique=False)
    op.create_index(op.f('ix_postmortem_corrective_actions_postmortem_id'), 'postmortem_corrective_actions', ['postmortem_id'], unique=False)
    op.add_column('incident_postmortems', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_postmortems', 'updated_at')
    op.drop_index(op.f('ix_postmortem_corrective_actions_postmortem_id'), table_name='postmortem_corrective_actions')
    op.drop_index(op.f('ix_postmortem_corrective_actions_id'), table_name='postmortem_corrective_actions')
    op.drop_table('postmortem_corrective_actions')
    # ### end Alembic commands ###
