"""add quiet hours to notification preferences

Revision ID: 82232616c350
Revises: 8ea4e1cbd013
Create Date: 2026-08-13 16:03:59.012057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82232616c350'
down_revision: Union[str, Sequence[str], None] = '8ea4e1cbd013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('quiet_hours_start', sa.Time(), nullable=True))
    op.add_column('notification_preferences', sa.Column('quiet_hours_end', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'quiet_hours_end')
    op.drop_column('notification_preferences', 'quiet_hours_start')
    # ### end Alembic commands ###
