"""add currency to factories

Revision ID: 87a417bc1485
Revises: 6acd81ae3201
Create Date: 2026-08-13 06:22:57.043639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a417bc1485'
down_revision: Union[str, Sequence[str], None] = '6acd81ae3201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factories', sa.Column('currency', sa.String(length=10), nullable=False, server_default='USD'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factories', 'currency')
    # ### end Alembic commands ###
