"""add device_alerts to notification_preferences

Revision ID: 8b7d330e58e8
Revises: 82232616c350
Create Date: 2026-08-14 04:26:54.418018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7d330e58e8'
down_revision: Union[str, Sequence[str], None] = '82232616c350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('device_alerts', sa.Boolean(), nullable=False, server_default='true'))
    op.alter_column('notification_preferences', 'device_alerts', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'device_alerts')
    # ### end Alembic commands ###
