"""add connection_config_encrypted to devices

Revision ID: 8bbd91991245
Revises: d10f77728bbf
Create Date: 2026-08-14 04:59:07.441590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bbd91991245'
down_revision: Union[str, Sequence[str], None] = 'd10f77728bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('connection_config_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'connection_config_encrypted')
    # ### end Alembic commands ###
