"""add duration_ms to job_runs

Revision ID: 95d423cb8c10
Revises: ff2f6edcf2a7
Create Date: 2026-08-13 13:25:37.892933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d423cb8c10'
down_revision: Union[str, Sequence[str], None] = 'ff2f6edcf2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_runs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_runs', 'duration_ms')
    # ### end Alembic commands ###
