"""extend device_energy_readings with raw_data and replay protection

Revision ID: 96eaf18f5318
Revises: bc959cbe3d86
Create Date: 2026-08-13 13:43:55.317942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96eaf18f5318'
down_revision: Union[str, Sequence[str], None] = 'bc959cbe3d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_energy_readings', sa.Column('voltage', sa.Float(), nullable=True))
    op.add_column('device_energy_readings', sa.Column('current', sa.Float(), nullable=True))
    op.add_column('device_energy_readings', sa.Column('frequency', sa.Float(), nullable=True))
    op.add_column('device_energy_readings', sa.Column('soc_percent', sa.Float(), nullable=True))
    op.add_column('device_energy_readings', sa.Column('temperature_c', sa.Float(), nullable=True))
    op.add_column('device_energy_readings', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint('uq_device_energy_readings_device_timestamp', 'device_energy_readings', ['device_id', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_device_energy_readings_device_timestamp', 'device_energy_readings', type_='unique')
    op.drop_column('device_energy_readings', 'raw_data')
    op.drop_column('device_energy_readings', 'temperature_c')
    op.drop_column('device_energy_readings', 'soc_percent')
    op.drop_column('device_energy_readings', 'frequency')
    op.drop_column('device_energy_readings', 'current')
    op.drop_column('device_energy_readings', 'voltage')
    # ### end Alembic commands ###
