"""add alert status lifecycle and structured metadata to notifications

Revision ID: 9f0b9024a7ba
Revises: 6f87b2117012
Create Date: 2026-08-13 09:46:12.817441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0b9024a7ba'
down_revision: Union[str, Sequence[str], None] = '6f87b2117012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('status', sa.String(length=20), nullable=False, server_default='UNREAD'))
    # Existing rows that were already marked read (Step 14) should carry
    # that forward as status='READ', not silently revert to UNREAD.
    op.execute("UPDATE notifications SET status = 'READ' WHERE is_read = true")
    op.add_column('notifications', sa.Column('rule_id', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('value', sa.Float(), nullable=True))
    op.add_column('notifications', sa.Column('threshold', sa.Float(), nullable=True))
    op.add_column('notifications', sa.Column('unit', sa.String(length=20), nullable=True))
    op.add_column('notifications', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('alert_metadata', sa.JSON(), nullable=True))
    op.add_column('notifications', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_notifications_rule_id'), 'notifications', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_rule_id'), table_name='notifications')
    op.drop_column('notifications', 'resolved_at')
    op.drop_column('notifications', 'alert_metadata')
    op.drop_column('notifications', 'source')
    op.drop_column('notifications', 'unit')
    op.drop_column('notifications', 'threshold')
    op.drop_column('notifications', 'value')
    op.drop_column('notifications', 'rule_id')
    op.drop_column('notifications', 'status')
    # ### end Alembic commands ###
