"""add notification preferences

Revision ID: b9653fbc2cc1
Revises: 9f0b9024a7ba
Create Date: 2026-08-13 09:50:24.622213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9653fbc2cc1'
down_revision: Union[str, Sequence[str], None] = '9f0b9024a7ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('battery_alerts', sa.Boolean(), nullable=False),
    sa.Column('price_alerts', sa.Boolean(), nullable=False),
    sa.Column('weather_alerts', sa.Boolean(), nullable=False),
    sa.Column('energy_alerts', sa.Boolean(), nullable=False),
    sa.Column('financial_alerts', sa.Boolean(), nullable=False),
    sa.Column('system_alerts', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('dashboard_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
