"""add device serial_number and key hash

Revision ID: bc959cbe3d86
Revises: 95d423cb8c10
Create Date: 2026-08-13 13:41:02.733489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc959cbe3d86'
down_revision: Union[str, Sequence[str], None] = '95d423cb8c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('serial_number', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('device_key_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'device_key_hash')
    op.drop_column('devices', 'serial_number')
    # ### end Alembic commands ###
