"""add data_quality to device_energy_readings

Revision ID: d10f77728bbf
Revises: 2365e3fa794e
Create Date: 2026-08-14 04:55:20.785406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10f77728bbf'
down_revision: Union[str, Sequence[str], None] = '2365e3fa794e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_energy_readings', sa.Column('data_quality', sa.String(length=20), nullable=False, server_default='GOOD'))
    op.alter_column('device_energy_readings', 'data_quality', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_energy_readings', 'data_quality')
    # ### end Alembic commands ###
