"""step77: add on_call_schedules table

Revision ID: d79a164452c7
Revises: 052_disaster_recovery
Create Date: 2026-08-14 09:43:34.080646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd79a164452c7'
down_revision: Union[str, Sequence[str], None] = '052_disaster_recovery'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('on_call_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_on_call_schedules_factory_id'), 'on_call_schedules', ['factory_id'], unique=False)
    op.create_index(op.f('ix_on_call_schedules_id'), 'on_call_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_on_call_schedules_user_id'), 'on_call_schedules', ['user_id'], unique=False)
    op.create_unique_constraint('uq_active_device_lock', 'control_locks', ['device_id', 'is_active'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_active_device_lock', 'control_locks', type_='unique')
    op.drop_index(op.f('ix_on_call_schedules_user_id'), table_name='on_call_schedules')
    op.drop_index(op.f('ix_on_call_schedules_id'), table_name='on_call_schedules')
    op.drop_index(op.f('ix_on_call_schedules_factory_id'), table_name='on_call_schedules')
    op.drop_table('on_call_schedules')
    # ### end Alembic commands ###
