"""add company fields to organization and prepare role migration

Revision ID: f2ca379d4467
Revises: b9653fbc2cc1
Create Date: 2026-08-13 10:00:05.452305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ca379d4467'
down_revision: Union[str, Sequence[str], None] = 'b9653fbc2cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('currency', sa.String(length=10), nullable=False, server_default='USD'))
    op.add_column('organizations', sa.Column('timezone', sa.String(length=100), nullable=False, server_default='UTC'))
    op.add_column('organizations', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))

    # Backfill a readable slug for existing orgs (nullable, but nicer
    # than leaving them blank) — lowercase, spaces to hyphens, suffixed
    # with the row id to guarantee uniqueness without a full slugify lib.
    op.execute(
        "UPDATE organizations SET slug = lower(regexp_replace(name, '[^a-zA-Z0-9]+', '-', 'g')) || '-' || id"
    )

    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)

    # Role vocabulary migration (Step 24) — backfill existing User rows
    # from the old vocabulary to the new one before anything starts
    # writing the new values.
    op.execute("UPDATE users SET role = 'COMPANY_ADMIN' WHERE role IN ('OWNER', 'ADMIN')")
    op.execute("UPDATE users SET role = 'FACTORY_MANAGER' WHERE role = 'OPERATOR'")
    op.execute("UPDATE users SET role = 'FINANCIAL_MANAGER' WHERE role = 'FINANCE_MANAGER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_column('organizations', 'is_active')
    op.drop_column('organizations', 'timezone')
    op.drop_column('organizations', 'currency')
    op.drop_column('organizations', 'phone')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'slug')
    # ### end Alembic commands ###
