"""add notification priority and acknowledgement

Revision ID: f676fac4dcad
Revises: 5c0e41b9373e
Create Date: 2026-08-13 15:57:29.048970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f676fac4dcad'
down_revision: Union[str, Sequence[str], None] = '5c0e41b9373e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('priority', sa.String(length=20), nullable=False, server_default='NORMAL'))
    op.alter_column('notifications', 'priority', server_default=None)
    op.add_column('notifications', sa.Column('acknowledged_by', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'notifications', 'users', ['acknowledged_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'acknowledged_at')
    op.drop_column('notifications', 'acknowledged_by')
    op.drop_column('notifications', 'priority')
    # ### end Alembic commands ###
